---
# CRI-O 컨테이너 런타임 업그레이드

- name: "CRI-O 업그레이드 시작"
  debug:
    msg: "CRI-O 컨테이너 런타임 업그레이드를 시작합니다"

# 초기 변수 설정
- name: "CRI-O 업그레이드 변수 초기화"
  set_fact:
    crio_needs_upgrade: false

# 현재 CRI-O 버전 확인
- name: "현재 CRI-O 버전 확인"
  shell: |
    if command -v crio >/dev/null 2>&1; then
      # crio version 명령어에서 버전 추출 (stdout 또는 stderr 모두 확인)
      version_output=$(crio version 2>&1)
      echo "$version_output" | grep -E "(crio version|RuntimeVersion|Starting CRI-O, version)" | head -1 | sed -E 's/.*version:? ([0-9]+\.[0-9]+\.[0-9]+).*/\1/' | sed 's/^v//'
    else
      echo "not_installed"
    fi
  register: crio_current_version
  changed_when: false

- name: "현재 CRI-O 버전 표시"
  debug:
    msg: "현재 CRI-O 버전: {{ crio_current_version.stdout }}"

# Kubernetes와 CRI-O 버전 호환성 매트릭스
- name: "CRI-O 목표 버전 결정"
  set_fact:
    crio_target_version: "{{ k8s_version_matrix[k8s_target_minor_version].crio_version }}"
    crio_minor_version: "{{ k8s_version_matrix[k8s_target_minor_version].crio_minor_version }}"
    crio_opensuse_available: "{{ k8s_version_matrix[k8s_target_minor_version].opensuse_available | default(false) }}"
  when: 
    - k8s_version_matrix[k8s_target_minor_version].crio_version is defined
    - k8s_version_matrix[k8s_target_minor_version].crio_minor_version is defined

- name: "CRI-O 목표 버전 표시"
  debug:
    msg: "CRI-O 목표 버전: {{ crio_target_version | default('N/A') }}"

# 실제 CRI-O 목표 버전 설정 (기존 로직 유지)
- name: "최종 CRI-O 목표 버전 표시"
  debug:
    msg: 
      - "CRI-O 마이너 버전: {{ crio_minor_version | default('N/A') }}"
      - "실제 사용 가능한 CRI-O 버전: {{ crio_target_version | default('N/A') }}"

# 버전 비교 및 업그레이드 필요 여부 확인
- name: "CRI-O 업그레이드 필요 여부 확인"
  set_fact:
    crio_needs_upgrade: "{{ crio_current_version.stdout != crio_target_version and crio_target_version is defined and crio_target_version != 'N/A' and crio_target_version != '' }}"

- name: "CRI-O 업그레이드 스킵"
  debug:
    msg: "CRI-O 업그레이드가 필요하지 않습니다 (현재: {{ crio_current_version.stdout }}, 목표: {{ crio_target_version | default('N/A') }})"
  when: not crio_needs_upgrade

# CRI-O 저장소 확인 변수 초기화
- name: "CRI-O 저장소 확인 변수 초기화"
  set_fact:
    crio_available_in_repo: false
  when: crio_needs_upgrade

# OpenSUSE 저장소 두 곳에서 CRI-O 패키지 확인
- name: "OpenSUSE 저장소 URL 구성"
  set_fact:
    # 1.28 이상 버전은 prerelease 저장소 사용
    opensuse_crio_prerelease_url: "{{ k8s_opensuse_crio_prerelease_base_url }}{{ crio_minor_version }}/rpm/x86_64/"
    # 1.27 이하 버전은 기존 stable 저장소 사용
    opensuse_crio_stable_url: "{{ k8s_opensuse_crio_base_url }}{{ crio_minor_version }}:{{ crio_target_version }}/{{ k8s_opensuse_os_version }}/x86_64/"
  when: 
    - crio_needs_upgrade
    - crio_minor_version is defined
    - crio_target_version is defined

- name: "OpenSUSE 저장소 URL 디버그"
  debug:
    msg:
      - "CRI-O 버전: {{ crio_target_version }}"
      - "마이너 버전: {{ crio_minor_version }}"
      - "Prerelease 저장소 (1.28+): {{ opensuse_crio_prerelease_url | default('N/A') }}"
      - "Stable 저장소 (1.27-): {{ opensuse_crio_stable_url | default('N/A') }}"
  when: crio_needs_upgrade

# 1.28 이상 버전: prerelease 저장소 확인
- name: "OpenSUSE prerelease 저장소 접근 가능성 확인"
  uri:
    url: "{{ opensuse_crio_prerelease_url }}"
    method: GET
    status_code: [200, 404]
    timeout: 30
  register: opensuse_prerelease_check
  when: 
    - crio_needs_upgrade
    - opensuse_crio_prerelease_url is defined
    - crio_minor_version is defined
    - crio_minor_version is version('1.28', '>=')
  ignore_errors: true

# 1.27 이하 버전: stable 저장소 확인
- name: "OpenSUSE stable 저장소 접근 가능성 확인 (1.27-)"
  uri:
    url: "{{ opensuse_crio_stable_url }}"
    method: GET
    status_code: [200, 404]
    timeout: 30
  register: opensuse_stable_check
  when: 
    - crio_needs_upgrade
    - opensuse_crio_stable_url is defined
    - crio_minor_version is defined
    - crio_minor_version is version('1.28', '<')
  ignore_errors: true

# 저장소 접근 결과 확인
- name: "OpenSUSE 저장소 접근 결과"
  debug:
    msg:
      - "Prerelease 저장소 (1.28+): {{ 'N/A' if opensuse_prerelease_check is not defined else ('접근 성공' if opensuse_prerelease_check.status is defined and opensuse_prerelease_check.status == 200 else '접근 실패') }}"
      - "Stable 저장소 (1.27-): {{ 'N/A' if opensuse_stable_check is not defined else ('접근 성공' if opensuse_stable_check.status is defined and opensuse_stable_check.status == 200 else '접근 실패') }}"
  when: 
    - crio_needs_upgrade
    - (opensuse_prerelease_check is defined or opensuse_stable_check is defined)

# 사용 가능한 저장소 URL 설정
- name: "사용 가능한 OpenSUSE 저장소 URL 설정"
  set_fact:
    opensuse_crio_repo_url: "{{ opensuse_crio_prerelease_url if (opensuse_prerelease_check is defined and opensuse_prerelease_check.status is defined and opensuse_prerelease_check.status == 200) else opensuse_crio_stable_url if (opensuse_stable_check is defined and opensuse_stable_check.status is defined and opensuse_stable_check.status == 200) else '' }}"
  when: 
    - crio_needs_upgrade
    - (opensuse_prerelease_check is defined or opensuse_stable_check is defined)

# 사용 가능한 저장소가 있는지 확인
- name: "OpenSUSE 저장소 사용 가능성 확인"
  set_fact:
    crio_available_in_repo: false
    opensuse_crio_available: "{{ opensuse_crio_repo_url is defined and opensuse_crio_repo_url != '' }}"
  when: crio_needs_upgrade

- name: "CRI-O 저장소 확인 디버깅"
  debug:
    msg:
      - "CRI-O 저장소 확인 결과:"
      - "  Prerelease 저장소 접근: {{ opensuse_prerelease_check.status | default('N/A') if opensuse_prerelease_check is defined and opensuse_prerelease_check.status is defined else 'N/A' }}"
      - "  Stable 저장소 접근: {{ opensuse_stable_check.status | default('N/A') if opensuse_stable_check is defined and opensuse_stable_check.status is defined else 'N/A' }}"
      - "  선택된 저장소 URL: {{ opensuse_crio_repo_url | default('없음') }}"
      - "  OpenSUSE 저장소 사용 가능: {{ opensuse_crio_available | default(false) }}"
  when: 
    - crio_needs_upgrade
    - (opensuse_prerelease_check is defined or opensuse_stable_check is defined)

- name: "CRI-O 저장소 상태 디버그"
  debug:
    msg:
      - "=== CRI-O 업그레이드 상태 요약 ==="
      - "업그레이드 필요: {{ crio_needs_upgrade }}"
      - "현재 CRI-O 버전: {{ crio_current_version.stdout | default('unknown') }}"
      - "목표 CRI-O 버전: {{ crio_target_version | default('N/A') }}"
      - "패키지 관리자: {{ k8s_detected_package_manager | default('unknown') }}"
      - "--- 저장소 상태 ---"
      - "Prerelease 저장소 (1.28+): {{ opensuse_crio_prerelease_url | default('N/A') }} (상태: {{ opensuse_prerelease_check.status | default('N/A') if opensuse_prerelease_check is defined and opensuse_prerelease_check.status is defined else 'N/A' }})"
      - "Stable 저장소 (1.27-): {{ opensuse_crio_stable_url | default('N/A') }} (상태: {{ opensuse_stable_check.status | default('N/A') if opensuse_stable_check is defined and opensuse_stable_check.status is defined else 'N/A' }})"
      - "선택된 저장소 URL: {{ opensuse_crio_repo_url | default('N/A') }}"
      - "OpenSUSE 저장소 사용 가능: {{ opensuse_crio_available | default(false) }}"
      - "--- 다음 단계 ---"
      - "{% if opensuse_crio_available | default(false) %}OpenSUSE 저장소에서 바이너리 설치 진행{% else %}CRI-O 설치 불가능{% endif %}"
  when: crio_needs_upgrade

# CRI-O 서비스 중지
- name: "CRI-O 서비스 중지"
  systemd:
    name: crio
    state: stopped
  register: crio_stop_result
  when: crio_needs_upgrade

- name: "CRI-O 서비스 중지 확인"
  debug:
    msg: "CRI-O 서비스 중지 {{ '성공' if crio_stop_result is succeeded else '실패' }}"
  when: 
    - crio_needs_upgrade
    - crio_stop_result is defined

# OpenSUSE 저장소에서 CRI-O 바이너리 설치
- name: "OpenSUSE 저장소 사용 가능성 확인"
  debug:
    msg: 
      - "OpenSUSE 저장소에서 CRI-O {{ crio_target_version }} 설치를 시도합니다."
      - "선택된 저장소 URL: {{ opensuse_crio_repo_url | default('없음') }}"
      - "OpenSUSE 저장소 사용 가능: {{ opensuse_crio_available | default(false) }}"
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)

- name: "OpenSUSE 저장소 접근 실패 시 중단"
  fail:
    msg: 
      - "모든 CRI-O 저장소에 접근할 수 없습니다."
      - "Prerelease 저장소 (1.28+): {{ opensuse_crio_prerelease_url | default('N/A') }} (상태: {{ opensuse_prerelease_check.status | default('N/A') if opensuse_prerelease_check is defined and opensuse_prerelease_check.status is defined else 'N/A' }})"
      - "Stable 저장소 (1.27-): {{ opensuse_crio_stable_url | default('N/A') }} (상태: {{ opensuse_stable_check.status | default('N/A') if opensuse_stable_check is defined and opensuse_stable_check.status is defined else 'N/A' }})"
      - "네트워크 연결을 확인하거나 수동으로 CRI-O를 설치해주세요."
  when: 
    - crio_needs_upgrade
    - not (opensuse_crio_available | default(false))

- name: "저장소 설정 문제로 인한 중단"
  fail:
    msg:
      - "CRI-O {{ crio_target_version }}를 설치할 수 있는 저장소를 찾을 수 없습니다!"
      - "Prerelease 저장소 (1.28+): {{ opensuse_crio_prerelease_url | default('N/A') }}"
      - "Stable 저장소 (1.27-): {{ opensuse_crio_stable_url | default('N/A') }}"
      - "선택된 저장소 URL: {{ opensuse_crio_repo_url | default('없음') }}"
      - "다음을 확인해주세요:"
      - "  1. CRI-O 저장소가 올바르게 설정되었는지"
      - "  2. 네트워크 연결 상태"
      - "  3. {{ crio_target_version }} 버전이 실제로 존재하는지"
  when:
    - crio_needs_upgrade  
    - not (opensuse_crio_available | default(false))

- name: "CRI-O 바이너리 다운로드 디렉토리 생성"
  file:
    path: /tmp/crio-upgrade
    state: directory
    mode: '0755'
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""

- name: "OpenSUSE 저장소에서 사용 가능한 CRI-O 패키지 목록 확인 (curl 사용)"
  shell: |
    curl -s -L "{{ opensuse_crio_repo_url }}" || echo "curl_failed"
  register: opensuse_package_list_curl
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""

- name: "저장소 응답 확인 (디버깅)"
  debug:
    msg: 
      - "curl 반환 코드: {{ opensuse_package_list_curl.rc | default('미정의') }}"
      - "응답 내용 길이: {{ opensuse_package_list_curl.stdout | default('') | length }}"
      - "응답 내용 일부: {{ opensuse_package_list_curl.stdout[:200] | default('내용 없음') }}..."
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)

- name: "사용 가능한 CRI-O 패키지 파일명 추출 (cri-o로 시작하는 rpm 파일)"
  set_fact:
    crio_package_name: "{{ opensuse_package_list_curl.stdout | default('') | regex_search('cri-o-[^\"\\s<>]*\\.rpm') }}"
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_package_list_curl is defined
    - opensuse_package_list_curl.stdout is defined
    - opensuse_package_list_curl.rc == 0

- name: "HTML에서 href 링크를 통한 CRI-O RPM 파일 찾기 (첫 번째 방법 실패 시)"
  set_fact:
    crio_package_name: "{{ opensuse_package_list_curl.stdout | default('') | regex_search('href=\"([^\"]*cri-o[^\"]*\\.rpm)\"', '\\1') | list | first | default('') }}"
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_package_list_curl is defined
    - opensuse_package_list_curl.stdout is defined
    - opensuse_package_list_curl.rc == 0
    - (crio_package_name is not defined or crio_package_name == "")

- name: "저장소 HTML 내용 디버깅"
  debug:
    msg: 
      - "저장소 URL: {{ opensuse_crio_repo_url | default('정의되지 않음') }}"
      - "HTML 내용 길이: {{ opensuse_package_list_curl.stdout | default('') | length }}"
      - "찾은 CRI-O 패키지: {{ crio_package_name | default('없음') }}"
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)

- name: "CRI-O 패키지 파일명 확인"
  debug:
    msg: "찾은 CRI-O 패키지: {{ crio_package_name | default('없음') }}"
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""

- name: "CRI-O 패키지명 존재 확인"
  fail:
    msg: 
      - "모든 저장소에서 CRI-O {{ crio_target_version }} 패키지를 찾을 수 없습니다."
      - "Prerelease 저장소 (1.28+): {{ opensuse_crio_prerelease_url | default('N/A') }}"
      - "Stable 저장소 (1.27-): {{ opensuse_crio_stable_url | default('N/A') }}"
      - "선택된 저장소 URL: {{ opensuse_crio_repo_url }}"
      - "CRI-O 업그레이드가 필수이므로 클러스터 업그레이드를 중단합니다."
      - "수동으로 CRI-O를 설치하거나 다른 버전을 시도해주세요."
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - (crio_package_name is not defined or crio_package_name == "")

- name: "실제 CRI-O RPM 패키지 다운로드"
  get_url:
    url: "{{ opensuse_crio_repo_url }}{{ crio_package_name }}"
    dest: "/tmp/crio-upgrade/{{ crio_package_name }}"
    mode: '0644'
  register: crio_download_result
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - crio_package_name is defined
    - crio_package_name != ""

- name: "CRI-O 패키지 다운로드 결과 확인"
  debug:
    msg: "CRI-O 패키지 다운로드 {{ '성공' if crio_download_result is succeeded else '실패' }}: {{ crio_package_name | default('패키지명 없음') }}"
  when: 
    - crio_needs_upgrade
    - crio_download_result is defined
    - crio_package_name is defined

- name: "CRI-O 패키지 다운로드 실패 시 중단"
  fail:
    msg: 
      - "CRI-O 패키지 다운로드가 실패했습니다: {{ crio_package_name }}"
      - "OpenSUSE 저장소 URL: {{ opensuse_crio_repo_url }}{{ crio_package_name }}"
      - "선택된 저장소에서 CRI-O 패키지를 다운로드할 수 없습니다."
      - "네트워크 연결 또는 저장소 문제를 확인해주세요."
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - crio_download_result is defined
    - crio_download_result is failed

- name: "CRI-O RPM 패키지 설치"
  yum:
    name: "/tmp/crio-upgrade/{{ crio_package_name }}"
    state: present
    disable_gpg_check: yes
  register: crio_install_result
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - crio_package_name is defined
    - crio_package_name != ""
    - crio_download_result is defined
    - crio_download_result is succeeded

- name: "CRI-O 패키지 설치 결과 확인"
  debug:
    msg: "CRI-O 패키지 설치 {{ '성공' if crio_install_result.rc == 0 else '실패' }}: {{ crio_package_name }}"
  when: 
    - crio_needs_upgrade
    - crio_install_result is defined

- name: "CRI-O 설치 실패 시 중단"
  fail:
    msg: 
      - "CRI-O RPM 패키지 설치가 실패했습니다: {{ crio_package_name }}"
      - "OpenSUSE 저장소에서 다운로드한 패키지 설치에 실패했습니다."
      - "수동으로 CRI-O를 설치하거나 시스템 의존성을 확인해주세요."
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - crio_install_result is defined
    - crio_install_result is failed

# CRI-O 설정 업데이트
- name: "CRI-O 설정 백업"
  copy:
    src: /etc/crio/crio.conf
    dest: "/etc/crio/crio.conf.backup.{{ ansible_date_time.epoch }}"
    remote_src: yes
  when: crio_needs_upgrade
  ignore_errors: true

- name: "CRI-O 구성 파일 업데이트"
  template:
    src: crio.conf.j2
    dest: /etc/crio/crio.conf
    backup: yes
    mode: '0644'
  when: crio_needs_upgrade
  notify:
    - restart crio

# CRI-O 서비스 재시작 및 활성화
- name: "systemd 데몬 리로드"
  systemd:
    daemon_reload: yes
  when: crio_needs_upgrade

- name: "CRI-O 서비스 재시작 및 활성화"
  systemd:
    name: crio
    state: restarted
    enabled: yes
  register: crio_restart_result
  when: crio_needs_upgrade

- name: "CRI-O 서비스 재시작 대기"
  wait_for:
    path: /var/run/crio/crio.sock
    timeout: 60
  when: crio_needs_upgrade

- name: "CRI-O 서비스 재시작 결과 확인"
  debug:
    msg: "CRI-O 서비스 재시작 {{ '성공' if crio_restart_result.status.ActiveState == 'active' else '실패' }}"
  when: 
    - crio_needs_upgrade
    - crio_restart_result is defined

# 업그레이드 후 검증
- name: "업그레이드된 CRI-O 버전 확인"
  shell: |
    if command -v crio >/dev/null 2>&1; then
      # crio version 명령어에서 버전 추출 (stdout 또는 stderr 모두 확인)
      version_output=$(crio version 2>&1)
      echo "$version_output" | grep -E "(crio version|RuntimeVersion|Starting CRI-O, version)" | head -1 | sed -E 's/.*version:? ([0-9]+\.[0-9]+\.[0-9]+).*/\1/' | sed 's/^v//'
    else
      echo "not_installed"
    fi
  register: crio_upgraded_version
  when: crio_needs_upgrade
  changed_when: false
  retries: 3
  delay: 5

- name: "CRI-O 서비스 상태 확인"
  systemd:
    name: crio
  register: crio_service_status
  when: crio_needs_upgrade

- name: "CRI-O 소켓 상태 확인"
  stat:
    path: /var/run/crio/crio.sock
  register: crio_socket_status
  when: crio_needs_upgrade

- name: "CRI-O 업그레이드 성공 여부 확인"
  set_fact:
    crio_upgrade_success: "{{ crio_upgraded_version.stdout == crio_target_version }}"
  when: 
    - crio_needs_upgrade
    - crio_upgraded_version is defined

- name: "CRI-O 업그레이드 실패 시 중단"
  fail:
    msg:
      - "CRI-O 업그레이드가 완전히 완료되지 않았습니다!"
      - "목표 버전: {{ crio_target_version }}"
      - "현재 버전: {{ crio_upgraded_version.stdout | default('확인 불가') }}"
      - "CRI-O 버전이 일치하지 않으므로 클러스터 업그레이드를 중단합니다."
      - "수동으로 CRI-O를 수정한 후 다시 시도해주세요."
  when: 
    - crio_needs_upgrade
    - crio_upgraded_version is defined
    - not (crio_upgrade_success | default(false))

# kubelet과 CRI-O 연결 테스트
- name: "kubelet 서비스 재시작 (CRI-O 연결 갱신)"
  systemd:
    name: kubelet
    state: restarted
  when: crio_needs_upgrade
  register: kubelet_restart_result

- name: "kubelet 재시작 후 대기"
  pause:
    seconds: 10
  when: crio_needs_upgrade

- name: "kubelet 서비스 상태 확인"
  systemd:
    name: kubelet
  register: kubelet_service_status
  when: crio_needs_upgrade

- name: "CRI-O와 kubelet 연결 테스트"
  shell: |
    timeout 30 crictl info >/dev/null 2>&1 && echo "연결 성공" || echo "연결 실패"
  register: crio_kubelet_connection
  when: crio_needs_upgrade
  changed_when: false
  ignore_errors: true

- name: "CRI-O 서비스 상태 검증"
  fail:
    msg:
      - "CRI-O 서비스가 정상적으로 실행되지 않습니다!"
      - "서비스 상태: {{ crio_service_status.status.ActiveState | default('확인 불가') }}"
      - "소켓 파일 존재: {{ crio_socket_status.stat.exists | default(false) }}"
      - "CRI-O/kubelet 연결: {{ crio_kubelet_connection.stdout | default('확인 불가') }}"
      - "'systemctl status crio' 명령어로 오류를 확인해주세요."
  when: 
    - crio_needs_upgrade
    - crio_service_status is defined
    - (crio_service_status.status.ActiveState != 'active' or 
       not (crio_socket_status.stat.exists | default(false)) or
       crio_kubelet_connection.stdout == '연결 실패')

- name: "CRI-O 업그레이드 결과 표시"
  debug:
    msg:
      - "=== CRI-O 업그레이드 완료 ==="
      - "이전 버전: {{ crio_current_version.stdout }}"
      - "업그레이드된 버전: {{ crio_upgraded_version.stdout | default('확인 불가') }}"
      - "업그레이드 성공: {{ crio_upgrade_success | default(false) }}"
      - "CRI-O 서비스 상태: {{ crio_service_status.status.ActiveState | default('확인 불가') }}"
      - "kubelet 서비스 상태: {{ kubelet_service_status.status.ActiveState | default('확인 불가') }}"
      - "소켓 파일 존재: {{ crio_socket_status.stat.exists | default(false) }}"
      - "CRI-O/kubelet 연결: {{ crio_kubelet_connection.stdout | default('확인 불가') }}"
  when: crio_needs_upgrade

# 임시 파일 정리
- name: "임시 다운로드 파일 정리"
  file:
    path: /tmp/crio-upgrade
    state: absent
  when: 
    - crio_needs_upgrade
    - opensuse_crio_available | default(false)

- name: "CRI-O 업그레이드 완료"
  debug:
    msg: "CRI-O 컨테이너 런타임 업그레이드가 완료되었습니다."
  when: crio_needs_upgrade