---
# CRI-O 컨테이너 런타임 업그레이드

- name: "CRI-O 업그레이드 시작"
  debug:
    msg: "CRI-O 컨테이너 런타임 업그레이드를 시작합니다"

# 초기 변수 설정
- name: "CRI-O 업그레이드 변수 초기화"
  set_fact:
    crio_needs_upgrade: false

# 현재 CRI-O 버전 확인
- name: "현재 CRI-O 버전 확인"
  shell: |
    if command -v crio >/dev/null 2>&1; then
      # crio version 명령어에서 버전 추출 (stdout 또는 stderr 모두 확인)
      version_output=$(crio version 2>&1)
      echo "$version_output" | grep -E "(crio version|RuntimeVersion|Starting CRI-O, version)" | head -1 | sed -E 's/.*version:? ([0-9]+\.[0-9]+\.[0-9]+).*/\1/' | sed 's/^v//'
    else
      echo "not_installed"
    fi
  register: crio_current_version
  changed_when: false

- name: "현재 CRI-O 버전 표시"
  debug:
    msg: "현재 CRI-O 버전: {{ crio_current_version.stdout }}"

# Kubernetes와 CRI-O 버전 호환성 매트릭스
- name: "CRI-O 목표 버전 결정"
  set_fact:
    crio_target_version: "{{ k8s_version_matrix[k8s_target_minor_version].crio_version }}"
    crio_minor_version: "{{ k8s_version_matrix[k8s_target_minor_version].crio_minor_version }}"
    crio_opensuse_available: "{{ k8s_version_matrix[k8s_target_minor_version].opensuse_available | default(false) }}"
  when: 
    - k8s_version_matrix[k8s_target_minor_version].crio_version is defined
    - k8s_version_matrix[k8s_target_minor_version].crio_minor_version is defined

- name: "CRI-O 목표 버전 표시"
  debug:
    msg: "CRI-O 목표 버전: {{ crio_target_version | default('N/A') }}"

# OpenSUSE 저장소에서 실제 사용 가능한 CRI-O 버전 확인
- name: "사용 가능한 CRI-O 패치 버전 목록 정의"
  set_fact:
    crio_patch_versions: ["{{ crio_minor_version }}.6", "{{ crio_minor_version }}.5", "{{ crio_minor_version }}.4", "{{ crio_minor_version }}.3", "{{ crio_minor_version }}.2", "{{ crio_minor_version }}.1"]
  when: 
    - crio_target_version is defined
    - crio_minor_version is defined
    - crio_opensuse_available | default(false)

- name: "OpenSUSE 저장소에서 사용 가능한 CRI-O 버전 확인"
  uri:
    url: "{{ k8s_opensuse_crio_base_url }}/{{ crio_minor_version }}:/{{ item }}/{{ k8s_opensuse_os_version }}/x86_64/"
    method: GET
    status_code: [200, 404]
  register: opensuse_version_check
  loop: "{{ crio_patch_versions }}"
  when: 
    - crio_target_version is defined
    - crio_minor_version is defined
    - crio_opensuse_available | default(false)
    - crio_patch_versions is defined
  ignore_errors: true

- name: "사용 가능한 첫 번째 CRI-O 버전 선택"
  set_fact:
    crio_actual_version: "{{ item.item }}"
    opensuse_crio_repo_url: "{{ k8s_opensuse_crio_base_url }}/{{ crio_minor_version }}:/{{ item.item }}/{{ k8s_opensuse_os_version }}/x86_64/"
  loop: "{{ opensuse_version_check.results }}"
  when: 
    - crio_target_version is defined
    - opensuse_version_check is defined
    - item.status == 200
    - crio_actual_version is not defined
  loop_control:
    label: "{{ item.item }}"

- name: "선택된 CRI-O 버전 디버그"
  debug:
    msg:
      - "시도한 버전들: {{ crio_patch_versions | default([]) }}"
      - "선택된 버전: {{ crio_actual_version | default('없음') }}"
      - "선택된 저장소 URL: {{ opensuse_crio_repo_url | default('N/A') }}"
  when: 
    - crio_target_version is defined
    - crio_minor_version is defined
    - crio_opensuse_available | default(false)

- name: "실제 CRI-O 목표 버전 설정"
  set_fact:
    crio_target_version: "{{ crio_actual_version }}"
  when: 
    - crio_actual_version is defined
    - crio_actual_version != ""

- name: "최종 CRI-O 목표 버전 표시"
  debug:
    msg: 
      - "CRI-O 마이너 버전: {{ crio_minor_version | default('N/A') }}"
      - "실제 사용 가능한 CRI-O 버전: {{ crio_target_version | default('N/A') }}"

# 버전 비교 및 업그레이드 필요 여부 확인
- name: "CRI-O 업그레이드 필요 여부 확인"
  set_fact:
    crio_needs_upgrade: "{{ crio_current_version.stdout != crio_target_version and crio_target_version is defined and crio_target_version != 'N/A' and crio_target_version != '' }}"

- name: "CRI-O 업그레이드 스킵"
  debug:
    msg: "CRI-O 업그레이드가 필요하지 않습니다 (현재: {{ crio_current_version.stdout }}, 목표: {{ crio_target_version | default('N/A') }})"
  when: not crio_needs_upgrade

# CRI-O 저장소 확인 변수 초기화
- name: "CRI-O 저장소 확인 변수 초기화"
  set_fact:
    crio_available_in_repo: false
  when: crio_needs_upgrade

# 공식 저장소에서 CRI-O 버전 확인
- name: "공식 저장소에서 CRI-O 버전 확인 (Rocky/RHEL)"
  shell: |
    if command -v yum >/dev/null 2>&1; then
      yum list available cri-o --showduplicates 2>/dev/null | grep "{{ crio_target_version }}" || echo "not_available"
    else
      echo "not_yum"
    fi
  register: crio_repo_check
  when: 
    - crio_needs_upgrade
    - k8s_detected_package_manager == 'yum'
  changed_when: false

- name: "공식 저장소에서 CRI-O 버전 확인 (Ubuntu/Debian)"
  shell: |
    if command -v apt >/dev/null 2>&1; then
      apt-cache madison cri-o 2>/dev/null | grep "{{ crio_target_version }}" || echo "not_available"
    else
      echo "not_apt"
    fi
  register: crio_repo_check
  when: 
    - crio_needs_upgrade
    - k8s_detected_package_manager == 'apt'
  changed_when: false

# 공식 저장소 사용 가능 여부 확인
- name: "공식 저장소 CRI-O 버전 사용 가능성 확인"
  set_fact:
    crio_available_in_repo: true
  when: 
    - crio_needs_upgrade
    - crio_repo_check is defined
    - crio_repo_check.stdout is defined
    - crio_repo_check.stdout != 'not_available'
    - "'not_available' not in crio_repo_check.stdout"

- name: "CRI-O 저장소 상태 디버그"
  debug:
    msg:
      - "CRI-O 업그레이드 필요: {{ crio_needs_upgrade }}"
      - "현재 CRI-O 버전: {{ crio_current_version.stdout | default('unknown') }}"
      - "목표 CRI-O 버전: {{ crio_target_version | default('N/A') }}"
      - "CRI-O 마이너 버전: {{ crio_minor_version | default('N/A') }}"
      - "OpenSUSE 저장소 지원: {{ crio_opensuse_available | default(false) }}"
      - "패키지 관리자: {{ k8s_detected_package_manager | default('unknown') }}"
      - "공식 저장소 사용 가능: {{ crio_available_in_repo | default(false) }}"
      - "OpenSUSE URL: {{ opensuse_crio_repo_url | default('N/A') }}"
      - "Fallback 패키지: {{ crio_fallback_package | default('N/A') }}"
  when: crio_needs_upgrade

# CRI-O 서비스 중지
- name: "CRI-O 서비스 중지"
  systemd:
    name: crio
    state: stopped
  register: crio_stop_result
  when: crio_needs_upgrade

- name: "CRI-O 서비스 중지 확인"
  debug:
    msg: "CRI-O 서비스 중지 {{ '성공' if not crio_stop_result.failed else '실패' }}"
  when: 
    - crio_needs_upgrade
    - crio_stop_result is defined

# 방법 1: 공식 저장소에서 CRI-O 업그레이드
- name: "공식 저장소에서 CRI-O 업그레이드 (Rocky/RHEL)"
  yum:
    name: "cri-o-{{ crio_target_version }}*"
    state: present
    update_cache: yes
  register: crio_official_yum_install
  when: 
    - crio_needs_upgrade
    - k8s_detected_package_manager == 'yum'
    - crio_available_in_repo | default(false)

- name: "공식 저장소에서 CRI-O 업그레이드 (Ubuntu/Debian)"
  apt:
    name: "cri-o={{ crio_target_version }}*"
    state: present
    update_cache: yes
  register: crio_official_apt_install
  when: 
    - crio_needs_upgrade
    - k8s_detected_package_manager == 'apt'
    - crio_available_in_repo | default(false)

- name: "공식 저장소 CRI-O 설치 결과 확인"
  debug:
    msg: 
      - "YUM 설치: {{ 'N/A' if crio_official_yum_install is not defined else ('성공' if not crio_official_yum_install.failed else '실패') }}"
      - "APT 설치: {{ 'N/A' if crio_official_apt_install is not defined else ('성공' if not crio_official_apt_install.failed else '실패') }}"
  when: 
    - crio_needs_upgrade
    - crio_available_in_repo | default(false)

- name: "공식 저장소 CRI-O 설치 실패 시 중단"
  fail:
    msg: "공식 저장소에서 CRI-O 설치가 실패했습니다"
  when: 
    - crio_needs_upgrade
    - crio_available_in_repo | default(false)
    - ((crio_official_yum_install is defined and crio_official_yum_install.failed) or 
       (crio_official_apt_install is defined and crio_official_apt_install.failed))

# 방법 2: 바이너리 방식으로 CRI-O 설치 (공식 저장소에 없는 경우)
- name: "OpenSUSE 저장소 사용 가능성 확인"
  debug:
    msg: "OpenSUSE 저장소에서 CRI-O {{ crio_target_version }} 사용 가능: {{ crio_opensuse_available | default(false) }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))

- name: "OpenSUSE 저장소에서 CRI-O 바이너리 다운로드 URL 확인"
  uri:
    url: "{{ opensuse_crio_repo_url | default('') | regex_replace('/x86_64/$', '/') }}"
    method: GET
    status_code: [200, 404]
  register: opensuse_repo_check
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
  ignore_errors: true

- name: "OpenSUSE 저장소 응답 확인"
  set_fact:
    opensuse_crio_available: "{{ opensuse_repo_check.status == 200 }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_repo_check is defined
    - opensuse_repo_check.status is defined

- name: "CRI-O 바이너리 다운로드 디렉토리 생성"
  file:
    path: /tmp/crio-upgrade
    state: directory
    mode: '0755'
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""

- name: "OpenSUSE 저장소에서 사용 가능한 CRI-O 패키지 목록 확인"
  uri:
    url: "{{ opensuse_crio_repo_url }}"
    method: GET
  register: opensuse_package_list
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""

- name: "사용 가능한 CRI-O 패키지 파일명 추출 (정확한 패턴 매칭)"
  set_fact:
    crio_package_name: "{{ opensuse_package_list.content | default('') | regex_search('cri-o-' + crio_target_version + '-[0-9]+\\.[0-9]+\\.el8\\.x86_64\\.rpm') }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - opensuse_package_list is defined
    - opensuse_package_list.content is defined

- name: "대체 패턴으로 CRI-O 패키지 파일명 추출 (첫 번째 패턴 실패 시)"
  set_fact:
    crio_package_name: "{{ opensuse_package_list.content | default('') | regex_search('cri-o-' + crio_target_version + '[^\"\\s]*\\.rpm') }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - opensuse_package_list is defined
    - opensuse_package_list.content is defined
    - (crio_package_name is not defined or crio_package_name == "")

- name: "CRI-O 패키지 파일명 확인"
  debug:
    msg: "찾은 CRI-O 패키지: {{ crio_package_name | default('없음') }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""

- name: "CRI-O 패키지명 존재 확인"
  fail:
    msg: "저장소에서 CRI-O {{ crio_target_version }} 패키지를 찾을 수 없습니다. 저장소 URL: {{ opensuse_crio_repo_url }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - (crio_package_name is not defined or crio_package_name == "")

- name: "실제 CRI-O RPM 패키지 다운로드"
  get_url:
    url: "{{ opensuse_crio_repo_url }}{{ crio_package_name }}"
    dest: "/tmp/crio-upgrade/{{ crio_package_name }}"
    mode: '0644'
  register: crio_download_result
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - crio_package_name is defined
    - crio_package_name != ""

- name: "CRI-O 패키지 다운로드 결과 확인"
  debug:
    msg: "CRI-O 패키지 다운로드 {{ '성공' if not crio_download_result.failed else '실패' }}: {{ crio_package_name }}"
  when: 
    - crio_needs_upgrade
    - crio_download_result is defined

- name: "CRI-O RPM 패키지 설치"
  yum:
    name: "/tmp/crio-upgrade/{{ crio_package_name }}"
    state: present
    disable_gpg_check: yes
  register: crio_install_result
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - crio_package_name is defined
    - crio_package_name != ""
    - crio_download_result is defined
    - not crio_download_result.failed

- name: "CRI-O 패키지 설치 결과 확인"
  debug:
    msg: "CRI-O 패키지 설치 {{ '성공' if crio_install_result.rc == 0 else '실패' }}: {{ crio_package_name }}"
  when: 
    - crio_needs_upgrade
    - crio_install_result is defined

- name: "CRI-O 설치 실패 시 중단"
  fail:
    msg: "CRI-O RPM 패키지 설치가 실패했습니다: {{ crio_package_name }}"
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))
    - opensuse_crio_repo_url is defined
    - opensuse_crio_repo_url != ""
    - crio_install_result is defined
    - crio_install_result.failed

# CRI-O 설정 업데이트
- name: "CRI-O 설정 백업"
  copy:
    src: /etc/crio/crio.conf
    dest: "/etc/crio/crio.conf.backup.{{ ansible_date_time.epoch }}"
    remote_src: yes
  when: crio_needs_upgrade
  ignore_errors: true

- name: "CRI-O 구성 파일 업데이트"
  template:
    src: crio.conf.j2
    dest: /etc/crio/crio.conf
    backup: yes
    mode: '0644'
  when: crio_needs_upgrade
  notify:
    - restart crio

# CRI-O 서비스 재시작 및 활성화
- name: "systemd 데몬 리로드"
  systemd:
    daemon_reload: yes
  when: crio_needs_upgrade

- name: "CRI-O 서비스 재시작 및 활성화"
  systemd:
    name: crio
    state: restarted
    enabled: yes
  register: crio_restart_result
  when: crio_needs_upgrade

- name: "CRI-O 서비스 재시작 대기"
  wait_for:
    path: /var/run/crio/crio.sock
    timeout: 60
  when: crio_needs_upgrade

- name: "CRI-O 서비스 재시작 결과 확인"
  debug:
    msg: "CRI-O 서비스 재시작 {{ '성공' if crio_restart_result.status.ActiveState == 'active' else '실패' }}"
  when: 
    - crio_needs_upgrade
    - crio_restart_result is defined

# 업그레이드 후 검증
- name: "업그레이드된 CRI-O 버전 확인"
  shell: |
    if command -v crio >/dev/null 2>&1; then
      # crio version 명령어에서 버전 추출 (stdout 또는 stderr 모두 확인)
      version_output=$(crio version 2>&1)
      echo "$version_output" | grep -E "(crio version|RuntimeVersion|Starting CRI-O, version)" | head -1 | sed -E 's/.*version:? ([0-9]+\.[0-9]+\.[0-9]+).*/\1/' | sed 's/^v//'
    else
      echo "not_installed"
    fi
  register: crio_upgraded_version
  when: crio_needs_upgrade
  changed_when: false
  retries: 3
  delay: 5

- name: "CRI-O 서비스 상태 확인"
  systemd:
    name: crio
  register: crio_service_status
  when: crio_needs_upgrade

- name: "CRI-O 소켓 상태 확인"
  stat:
    path: /var/run/crio/crio.sock
  register: crio_socket_status
  when: crio_needs_upgrade

- name: "CRI-O 업그레이드 성공 여부 확인"
  set_fact:
    crio_upgrade_success: "{{ crio_upgraded_version.stdout == crio_target_version }}"
  when: 
    - crio_needs_upgrade
    - crio_upgraded_version is defined

- name: "CRI-O 업그레이드 실패 경고"
  debug:
    msg:
      - "경고: CRI-O 업그레이드가 완전히 완료되지 않았습니다!"
      - "목표 버전: {{ crio_target_version }}"
      - "현재 버전: {{ crio_upgraded_version.stdout | default('확인 불가') }}"
      - "수동으로 'systemctl restart crio'와 'systemctl restart kubelet'을 실행하세요."
  when: 
    - crio_needs_upgrade
    - not (crio_upgrade_success | default(false))

# kubelet과 CRI-O 연결 테스트
- name: "kubelet 서비스 재시작 (CRI-O 연결 갱신)"
  systemd:
    name: kubelet
    state: restarted
  when: crio_needs_upgrade
  register: kubelet_restart_result

- name: "kubelet 재시작 후 대기"
  pause:
    seconds: 10
  when: crio_needs_upgrade

- name: "kubelet 서비스 상태 확인"
  systemd:
    name: kubelet
  register: kubelet_service_status
  when: crio_needs_upgrade

- name: "CRI-O와 kubelet 연결 테스트"
  shell: |
    timeout 30 crictl info >/dev/null 2>&1 && echo "연결 성공" || echo "연결 실패"
  register: crio_kubelet_connection
  when: crio_needs_upgrade
  changed_when: false
  ignore_errors: true

- name: "CRI-O 업그레이드 결과 표시"
  debug:
    msg:
      - "=== CRI-O 업그레이드 완료 ==="
      - "이전 버전: {{ crio_current_version.stdout }}"
      - "업그레이드된 버전: {{ crio_upgraded_version.stdout | default('확인 불가') }}"
      - "업그레이드 성공: {{ crio_upgrade_success | default(false) }}"
      - "CRI-O 서비스 상태: {{ crio_service_status.status.ActiveState | default('확인 불가') }}"
      - "kubelet 서비스 상태: {{ kubelet_service_status.status.ActiveState | default('확인 불가') }}"
      - "소켓 파일 존재: {{ crio_socket_status.stat.exists | default(false) }}"
      - "CRI-O/kubelet 연결: {{ crio_kubelet_connection.stdout | default('확인 불가') }}"
  when: crio_needs_upgrade

# 임시 파일 정리
- name: "임시 다운로드 파일 정리"
  file:
    path: /tmp/crio-upgrade
    state: absent
  when: 
    - crio_needs_upgrade
    - not (crio_available_in_repo | default(false))

- name: "CRI-O 업그레이드 완료"
  debug:
    msg: "CRI-O 컨테이너 런타임 업그레이드가 완료되었습니다."
  when: crio_needs_upgrade 