---
# Kubernetes 클러스터 업그레이드 메인 태스크

- name: "K8s 업그레이드 시작 로그"
  debug:
    msg: "Kubernetes 클러스터 업그레이드를 시작합니다"

# 01. 사전 검사 및 환경 준비
- name: "01. 사전 검사 수행"
  include_tasks: 01_preflight.yml
  tags:
    - preflight
    - always

# 02. 현재 버전 감지
- name: "02. 현재 Kubernetes 버전 감지"
  include_tasks: 02_detect_version.yml
  tags:
    - detect
    - always

# 03. 목표 버전 결정
- name: "03. 목표 버전 결정"
  include_tasks: 03_determine_target.yml
  tags:
    - target
    - always

# 04. 노드 역할 감지
- name: "04. 노드 역할 감지"
  include_tasks: 04_detect_role.yml
  tags:
    - role
    - always

# 05. 패키지 관리자 감지
- name: "05. 패키지 관리자 감지"
  include_tasks: 05_detect_package_manager.yml
  tags:
    - package
    - always

# 06. 공식 repo 버전 체크
- name: "06. 공식 repo 버전 체크"
  include_tasks: 06_check_official_repo.yml
  tags:
    - repo-check
    - always

# 07. 백업 수행
- name: "07. 백업 수행"
  include_tasks: 07_backup.yml
  when: k8s_backup_enabled
  tags:
    - backup

# 08. 마스터 노드 업그레이드 (control_plane 단계에서만)
- name: "08. 첫 번째 컨트롤 플레인 업그레이드"
  include_tasks: 08_upgrade_control_plane.yml
  when: 
    - k8s_upgrade_phase | default('') == 'control_plane'
    - k8s_detected_role == 'master'
    - inventory_hostname == groups['control_plane'][0] | default(groups['all'][0])
  tags:
    - control-plane
    - master

# 09. 추가 마스터 노드 업그레이드
- name: "09. 추가 컨트롤 플레인 노드 업그레이드"
  include_tasks: 09_upgrade_other_masters.yml
  when: 
    - k8s_upgrade_phase | default('') == 'control_plane'
    - k8s_detected_role == 'master'
    - inventory_hostname != groups['control_plane'][0] | default(groups['all'][0])
  tags:
    - control-plane
    - other-masters

# 10. 워커 노드 업그레이드 (worker 단계에서만)
- name: "10. 워커 노드 업그레이드"
  include_tasks: 10_upgrade_worker.yml
  when: 
    - k8s_upgrade_phase | default('') == 'worker'
    - k8s_detected_role == 'worker'
  tags:
    - worker

# 11. 업그레이드 후 검증
- name: "11. 업그레이드 검증"
  include_tasks: 11_verify.yml
  when: k8s_verify_upgrade
  tags:
    - verify
    - always

# 12. 정리 작업
- name: "12. 정리 작업"
  include_tasks: 12_cleanup.yml
  tags:
    - cleanup
    - always

- name: "K8s 업그레이드 완료 로그"
  debug:
    msg: "Kubernetes 클러스터 업그레이드가 완료되었습니다. 버전: {{ k8s_current_version }} -> {{ k8s_target_version }}" 