---
- name: ssh-key generate, ssh-key deploy
  hosts: every
  gather_facts: false
  ignore_errors: true

  tasks:
    - name: ssh-key generate
      connection: local
      command: "ssh-keygen -t rsa -b 3072 -f ~/.ssh/id_rsa -q -N ''"
      run_once: true
      
    - name: ssh-key deploy
      authorized_key:
        user: root
        state: present
        key: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"